// import 'package:firebase_user_avatar_flutter/services/firebase_auth_service.dart';
// import 'package:firebase_user_avatar_flutter/services/firebase_storage_service.dart';
// import 'package:firebase_user_avatar_flutter/services/firestore_service.dart';
// import 'package:flutter/material.dart';
// import 'package:provider/provider.dart';

// /// Used to create user-dependant objects that need to be accessible by all widgets.
// /// This widget should live above the [MaterialApp].
// /// See [AuthWidget], a descendant widget that consumes the snapshot generated by this builder.
